name: Continuous Delivery Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          mkdir build
          cp index.html javascript.js styles.css build/
      
      - name: Deploy to GitHub Pages
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      
      - name: Measure Deployment Metrics
        run: |
          echo "Deployment Frequency: 1 deployment"
          if [ ${{ steps.deploy.outcome }} == 'success' ]; then
            echo "Deployment Success Rate: 100%" > metrics.txt
          else
            echo "Deployment Success Rate: 0%" > metrics.txt
          fi
      
      - name: Measure Response Time
        run: |
          response_time=$(curl -o /dev/null -s -w "%{time_total}\n" https://your-username.github.io/your-repo-name/)
          echo "Response Time: $response_time seconds" >> metrics.txt
      
      - name: Upload Metrics as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: metrics
          path: metrics.txt

