name: Continuous Delivery Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: |
          mkdir build
          cp index.html javascript.js styles.css build/
      

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Measure Page Load Time
        run: |
          response_time=$(curl -o /dev/null -s -w "%{time_total}\n" https://your-username.github.io/your-repo-name/)
          echo "Page Load Time: $response_time seconds"

      - name: Measure Deployment Metrics
        run: |
          echo "Deployment Frequency: 1 deployment"
          if [ ${{ steps.deployment.outcome }} == 'success' ]; then
            echo "Deployment Success Rate: 100%"
          else
            echo "Deployment Success Rate: 0%"
          fi
